# Generated by Django 5.1.3 on 2024-11-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drum_oee.cause')),
            ],
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('order', models.CharField(blank=True, max_length=20, null=True, verbose_name='Заказ')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drum_oee.status', verbose_name='Статус')),
            ],
        ),
    ]
