# Generated by Django 5.1.3 on 2024-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drum_oee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='drum_type',
            field=models.CharField(blank=True, choices=[('closed', 'Закрытый верх'), ('open', 'Открытый верх')], max_length=6, null=True, verbose_name='Тип бочки'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
