# Generated by Django 5.1.3 on 2025-01-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_currentproduction_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentproduction',
            name='updated_at',
        ),
    ]
