# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest
    
    steps:
      # Получаем код из репозитория
      - uses: actions/checkout@v3

      # Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Используем секреты из GitHub для подключения
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
          # Команды выполняемые на сервере
          script: |
            # Переходим в директорию проекта
            cd /home/v/OEE
            
            # Обновляем код из репозитория (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S git pull
            
            # Активируем виртуальное окружение
            source venv/bin/activate
            
            # Обновляем зависимости
            pip install -r requirements.txt
            
            # Создаем файл .env из отдельных секретов
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env

            # Выполняем миграции
            python manage.py migrate --noinput

            # Собираем статику
            python manage.py collectstatic --noinput
            
            # Перезапускаем gunicorn вместо django_consalt
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart gunicorn